# Generated by Django 4.1.2 on 2022-11-22 18:04

import datetime
from django.db import migrations, models
import phone_field.models
import users.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2022, 11, 22), validators=[users.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmed',
            field=models.PositiveIntegerField(default=0, verbose_name='Подтверждено'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Номер телефона'),
        ),
    ]
