# Generated by Django 4.1.2 on 2023-05-20 18:31

import datetime
from django.db import migrations, models
import users.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.date(2023, 5, 20), validators=[users.validators.validators.validate_age], verbose_name='Дата рождения'),
        ),
    ]
