# Generated by Django 4.1.2 on 2023-05-20 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_genre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
